---
title: "Untitled"
output: html_document
date: "2025-09-10"
---

```{r setup, include=FALSE}
library(sswids)
library(sf)
library(dplyr)
library(tidyselect)
library(ggplot2)
library(gridExtra)
library(patchwork)
library(crayon)

sswids::connect_to_sswidb(db_version = 'PROD')

BearDeerTurkey0.95 <- readRDS("./BearDeerTurkeyList.rds")


Deer <- BearDeerTurkey0.95[["Deer"]]%>%st_join(get_spatial_data("dmus")%>%st_transform(., 4326))%>%select(-c(18,19,21:25))

DMUold <- st_read("C:/Users/wildeefb/Documents/GeoSpatial/WI_Deer_Mgmt_Units_Zones_2014/WI_Deer_Mgmt_Units_Zones_2014.shp")
DMUoldnoSub <- DMUold%>%group_by(DEER_MANAG, DEER_MGMT_)%>%summarise(geometry=st_union(geometry))
DMUoldnoSub$ZoneUnit <- paste(DMUoldnoSub$DEER_MANAG, DMUoldnoSub$DEER_MGMT_, sep="-")
Deer2 <- st_join(Deer[,-c(17,18)], st_transform(st_make_valid(DMUoldnoSub), 4326))

```

```{r tables, message=FALSE}
Deer2%>%group_by(ZoneUnit, season)%>%summarise(ncams=length(unique(cam_site_id)))
Deer2%>%group_by(ZoneUnit, season)%>%summarise(ncams=length(unique(cam_site_id)))%>%filter(ncams == 0)
```


```{r whole pop, message=FALSE, include=FALSE}
#Whole population
combine_cols=TRUE
spatialgroup <- "ZoneUnit"
ZoneUnits <- unique(DMUoldnoSub$ZoneUnit)
ZoneUnits <- ZoneUnits[-which(ZoneUnits == "Northern Forest Zone-Apostle Islands")]
ZoneList <- lapply(1:length(ZoneUnits), function (z) {
  print(ZoneUnits[z])
  #filter dataframe down to specific zone-unit
df <- Deer2%>%filter(ZoneUnit == ZoneUnits[z])
#make table for number of camera sites by year and prep for inclusion in plot
camtable <- df%>%group_by(season)%>%summarise(ncams=length(unique(cam_site_id)), year=unique(season +2018))%>%
  st_drop_geometry()%>% select(-season)%>%relocate(year)
camtableGrob <- tableGrob(camtable)
#recreate date ranges from data frame
daterange <- df%>%group_by(season)%>% 
    dplyr::summarise(start_date=as.Date(min(start_date)), end_date=as.Date(max(end_date)))%>%
    sf::st_drop_geometry()
#combine different [A-Z]*_AMT columns? check combine_cols argument above
 if(length(grep(pattern = "[A-Z]*_AMT", x = colnames(df), value = TRUE)) > 1 & combine_cols == TRUE){
  df <- sswids:::combine_species_cols(conn = conn, df=df) # helper function can be found in utils.R
 }
df.byocc <- df %>%
    filter(days_active >= 4) %>%
    filter(prop_classified >= 0.95) %>%
    mutate(across(matches("[A-Z]*_AMT", ignore.case = FALSE), ~ifelse(.>0,1,0), .names = "{sub('_AMT', '_binary',col)}")) %>%
    group_by(season,occ,.data[[spatialgroup]]) %>%
    dplyr::summarise(across(matches("[A-Z]*_AMT", ignore.case = FALSE), ~sum(.),.names = "{sub('_AMT', '_sum',col)}"),
              across(matches("[A-Z]*_binary", ignore.case = FALSE), ~sum(.),.names = "{sub('_binary', '_occ',col)}"),
              num.sites = dplyr::n(),
              num.days = sum(days_active)) %>%
    mutate(across(matches("[A-Z]*_occ", ignore.case = FALSE), ~./num.sites,.names = "{sub('_occ', '_propocc',col)}"),
           across(matches("[A-Z]*_sum", ignore.case = FALSE), ~./num.days,
                  .names = "{sub('_sum','_trigsperday',col)}"))%>%
    mutate(yearocc = paste0(lubridate::year(min(daterange$start_date))+(season-1),stringr::str_pad(occ, width=2, side="left", pad="0"))) %>%
    dplyr::arrange(yearocc) %>%
    group_by(yearocc) %>%
    mutate(time = dplyr::cur_group_id())
df.byocc.long = df.byocc %>%
    select(time, season,occ,any_of(spatialgroup),num.sites,
           matches("_occ")) %>%
    tidyr::pivot_longer(cols=matches("_occ"), names_pattern  = "(.*)_occ", names_to = "Spp")%>%
    mutate(year=season+2018) #this may need to be modified

  df.byocc.long[[spatialgroup]] <- as.factor(df.byocc.long[[spatialgroup]])
  df.byocc.long$binomresponse <- with(df.byocc.long, cbind(value, num.sites - value))
  species <- stringr::str_extract(colnames(df), pattern =  ".*_AMT")
  specieslist <- species[species != "" & !is.na(species)]


  cat("Making plots for:", specieslist)

  titles <- janitor::make_clean_names(sub("(FOX|SKUNK)(.*)", "\\2 \\1", x = unique(df.byocc.long$Spp)), case = "title")
  nspecies <- length(specieslist)
  
   binomlist <- lapply(seq(1:nspecies), function(i){
    speciesframe <- filter(df.byocc.long, grepl(Spp, pattern = unique(df.byocc.long$Spp)[1]))
    colnames(speciesframe)[which(colnames(speciesframe) == spatialgroup)] <- "zone" #can't handle multiple spatial groups

    nocc <- length(unique(speciesframe$occ))
    knots <- list(occ = c(0.5, nocc+0.5))
    nyears <- length(unique(speciesframe$season))


    #model with year x occ interaction as well as occ x zone interaction
    m2y <- try(mgcv::gam(binomresponse ~  s(season, k=nyears, by=zone) + s(occ, bs = "cc", k=nocc, by=zone) +
                       ti(season, occ, bs = c("tp", "cc")),
               data = speciesframe,
               family = binomial,
               knots = knots) #zone +)
                )
  if(inherits(m2y, "try-error")) {
    plottemp2 <- NULL
    } else{



    newdatay <- expand.grid(season=unique(speciesframe$season), zone=unique(speciesframe$zone), occ=nocc/2)

    occeffects <- paste("s(occ)", paste0("zone",unique(speciesframe$zone)), sep=":")
    #predict just year trend
    yrtrendm2y <- gratia::fitted_values(m2y, data=newdatay, exclude=c(occeffects,"ti(season,occ)"))%>%mutate(time=rep(seq(nocc/2, length.out=nyears, by=nocc),length(unique(speciesframe$zone))))


    #predict whole model

    occtrendm2y <- gratia::fitted_values(m2y)%>%mutate(time=(season-1)*52 + occ)



    plottemp <-  ggplot() +
      geom_line(data=occtrendm2y, aes(x = time, y = .fitted, color=zone), lwd=0.5) +
      geom_line(data=yrtrendm2y, aes(x = time, y = .fitted, color=zone), lwd=2) +
      geom_pointrange(data=yrtrendm2y, aes(x= time, y= .fitted,ymin = .lower_ci, ymax = .upper_ci, color=zone), size=1, lwd=1) +
      labs(title=stringr::str_wrap(sprintf("Weekly Proportion of Snapshot Camera Sites with %s detections", titles[i]),75),
           y = "Proportion of sites",
           x = "Time",
           subtitle = sprintf("Year Round, %s - %s", min(speciesframe$year), max(speciesframe$year))) +
      geom_vline(xintercept=seq(1,(nocc+1)*nyears,nocc)) +
      scale_x_continuous(labels = seq(min(speciesframe$year),max(speciesframe$year),1), breaks = seq(nocc/2,nocc*nyears,nocc)) +
      scale_color_brewer(palette = "Set2",
                         name = "Mgmt Zone",
                         labels = unique(speciesframe$zone)) +
      scale_fill_brewer(palette = "Set2",
                        name = "Mgmt Zone",
                        labels = unique(speciesframe$zone))
    tableplot <- ggplot() + theme_void() + 
  annotation_custom(camtableGrob)
    
    plottemp2 <- plottemp + tableplot + plot_layout(ncol = 1)
    }
    return(plottemp2)
  })
  
  names(binomlist) <- specieslist
  return(binomlist)
})

names(ZoneList) <- ZoneUnits
saveRDS(ZoneList)
```


```{r SexAge, message=FALSE, include=FALSE}
#Different Sex/Age Classes
combine_cols=FALSE
spatialgroup <- "ZoneUnit"
ZoneUnits <- unique(DMUoldnoSub$ZoneUnit)
ZoneUnits <- ZoneUnits[-which(ZoneUnits == "Northern Forest Zone-Apostle Islands")]
ZoneListSexAge <- lapply(1:length(ZoneUnits), function (z) {
  print(ZoneUnits[z])
df <- Deer2%>%filter(ZoneUnit == ZoneUnits[z])
camtable <- df%>%group_by(season)%>%summarise(ncams=length(unique(cam_site_id)), year=unique(season +2018))%>%
  st_drop_geometry()%>% select(-season)%>%relocate(year)
camtableGrob <- tableGrob(camtable)
daterange <- df%>%group_by(season)%>% #recreate date ranges from data frame
    dplyr::summarise(start_date=as.Date(min(start_date)), end_date=as.Date(max(end_date)))%>%
    sf::st_drop_geometry()
 if(length(grep(pattern = "[A-Z]*_AMT", x = colnames(df), value = TRUE)) > 1 & combine_cols == TRUE){
  df <- sswids:::combine_species_cols(conn = conn, df=df) # helper function can be found in utils.R
 }
df.byocc <- df %>%
    filter(days_active >= 4) %>%
    filter(prop_classified >= 0.95) %>%
    mutate(across(matches("[A-Z]*_AMT", ignore.case = FALSE), ~ifelse(.>0,1,0), .names = "{sub('_AMT', '_binary',col)}")) %>%
    group_by(season,occ,.data[[spatialgroup]]) %>%
    dplyr::summarise(across(matches("[A-Z]*_AMT", ignore.case = FALSE), ~sum(.),.names = "{sub('_AMT', '_sum',col)}"),
              across(matches("[A-Z]*_binary", ignore.case = FALSE), ~sum(.),.names = "{sub('_binary', '_occ',col)}"),
              num.sites = dplyr::n(),
              num.days = sum(days_active)) %>%
    mutate(across(matches("[A-Z]*_occ", ignore.case = FALSE), ~./num.sites,.names = "{sub('_occ', '_propocc',col)}"),
           across(matches("[A-Z]*_sum", ignore.case = FALSE), ~./num.days,
                  .names = "{sub('_sum','_trigsperday',col)}"))%>%
    mutate(yearocc = paste0(lubridate::year(min(daterange$start_date))+(season-1),stringr::str_pad(occ, width=2, side="left", pad="0"))) %>%
    dplyr::arrange(yearocc) %>%
    group_by(yearocc) %>%
    mutate(time = dplyr::cur_group_id())
df.byocc.long = df.byocc %>%
    select(time, season,occ,any_of(spatialgroup),num.sites,
           matches("_occ")) %>%
    tidyr::pivot_longer(cols=matches("_occ"), names_pattern  = "(.*)_occ", names_to = "Spp")%>%
    mutate(year=season+2018) #this may need to be modified

  df.byocc.long[[spatialgroup]] <- as.factor(df.byocc.long[[spatialgroup]])
  df.byocc.long$binomresponse <- with(df.byocc.long, cbind(value, num.sites - value))
  species <- stringr::str_extract(colnames(df), pattern =  ".*_AMT")
  specieslist <- species[species != "" & !is.na(species)]


  cat("Making plots for:", specieslist)

  titles <- janitor::make_clean_names(sub("(FOX|SKUNK)(.*)", "\\2 \\1", x = unique(df.byocc.long$Spp)), case = "title")
  nspecies <- length(specieslist)
  
   binomlist <- lapply(seq(1:nspecies), function(i){
    speciesframe <- filter(df.byocc.long, grepl(Spp, pattern = unique(df.byocc.long$Spp)[i]))
    colnames(speciesframe)[which(colnames(speciesframe) == spatialgroup)] <- "zone" #can't handle multiple spatial groups

    nocc <- length(unique(speciesframe$occ))
    knots <- list(occ = c(0.5, nocc+0.5))
    nyears <- length(unique(speciesframe$season))


    #model with year x occ interaction as well as occ x zone interaction
    m2y <- try(mgcv::gam(binomresponse ~  s(season, k=nyears, by=zone) + s(occ, bs = "cc", k=nocc, by=zone) +
                       ti(season, occ, bs = c("tp", "cc")),
               data = speciesframe,
               family = binomial,
               knots = knots) #zone +)
                )
  if(inherits(m2y, "try-error")) {
    plottemp2 <- NULL
    } else{



    newdatay <- expand.grid(season=unique(speciesframe$season), zone=unique(speciesframe$zone), occ=nocc/2)

    occeffects <- paste("s(occ)", paste0("zone",unique(speciesframe$zone)), sep=":")
    #predict just year trend
    yrtrendm2y <- gratia::fitted_values(m2y, data=newdatay, exclude=c(occeffects,"ti(season,occ)"))%>%mutate(time=rep(seq(nocc/2, length.out=nyears, by=nocc),length(unique(speciesframe$zone))))


    #predict whole model

    occtrendm2y <- gratia::fitted_values(m2y)%>%mutate(time=(season-1)*52 + occ)



    plottemp <-  ggplot() +
      geom_line(data=occtrendm2y, aes(x = time, y = .fitted, color=zone), lwd=0.5) +
      geom_line(data=yrtrendm2y, aes(x = time, y = .fitted, color=zone), lwd=2) +
      geom_pointrange(data=yrtrendm2y, aes(x= time, y= .fitted,ymin = .lower_ci, ymax = .upper_ci, color=zone), size=1, lwd=1) +
      labs(title=stringr::str_wrap(sprintf("Weekly Proportion of Snapshot Camera Sites with %s detections", titles[i]),75),
           y = "Proportion of sites",
           x = "Time",
           subtitle = sprintf("Year Round, %s - %s", min(speciesframe$year), max(speciesframe$year))) +
      geom_vline(xintercept=seq(1,(nocc+1)*nyears,nocc)) +
      scale_x_continuous(labels = seq(min(speciesframe$year),max(speciesframe$year),1), breaks = seq(nocc/2,nocc*nyears,nocc)) +
      scale_color_brewer(palette = "Set2",
                         name = "Mgmt Zone",
                         labels = unique(speciesframe$zone)) +
      scale_fill_brewer(palette = "Set2",
                        name = "Mgmt Zone",
                        labels = unique(speciesframe$zone))
    
    tableplot <- ggplot() + theme_void() +
  annotation_custom(camtableGrob)
    
    plottemp2 <- plottemp + tableplot + plot_layout(ncol = 1)
    }
    return(plottemp2)
  })
  
  names(binomlist) <- specieslist
  return(binomlist)
})

names(ZoneListSexAge) <- ZoneUnits
```

```{r remove nulls}
#removes list items where nested list items are null (1 graph)
ZoneList2 <- ZoneList[sapply(ZoneList, function(x) sapply(x, function(y) any(!is.null(y))))]

#removes list items where nested list items are null (4 graphs)
ZoneListSexAge2 <- ZoneListSexAge[sapply(ZoneListSexAge, function(x) any(sapply(x, function(y) !is.null(y))))]
```



# Zone Units Temporal Plots
```{r ZoneUnitLoop,echo=FALSE,message=FALSE,results="asis"}

attach(ZoneList2)
attach(ZoneListSexAge2)
for(i in names(ZoneList2)) {
  cat("\n###", blue(i), blue("Temporal Trends"),"  \n")
  #print(plot(airquality[airquality$Month == i,]))
  print(ZoneList2[[i]][[1]])
  print(ZoneListSexAge2[[i]][[1]])
  print(ZoneListSexAge2[[i]][[2]])
  print(ZoneListSexAge2[[i]][[4]])
  cat("  \n")
}
```


